name: Deploy redirector

on:
  push:
    branches: ['main']
    tags: ['v*']

env:
  REGISTRY: git.dyakov.space

jobs:
  deploy-testing:
    name: Deploy Testing
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted, Linux, testing]
    environment:
      name: Testing
      url: https://to.test.profcomff.com/
    permissions:
      packages: read
    env:
      PROJECT_VERSION: dev-latest
      PROJECT_NAME: com_profcomff_redirect_test
      CONTAINER_SUFFIX: _test
      DB_DSN: ${{ secrets.DB_DSN }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
      BASE_URL: ${{ vars.BASE_URL }}
      OIDC_CONFIGURATION_URI: ${{ vars.OIDC_CONFIGURATION_URI }}
      OIDC_CLIENT_ID: ${{ vars.OIDC_CLIENT_ID }}
      OIDC_ADMIN_CLAIM: ${{ vars.OIDC_ADMIN_CLAIM }}
      OIDC_ADMIN_CLAIM_VALUE: ${{ vars.OIDC_ADMIN_CLAIM_VALUE }}
      ALLOWED_DOMAINS: ${{ vars.ALLOWED_DOMAINS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to git.dyakov.space
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: robot-profcomff
          password: ${{ secrets.DYAKOVSPACE_CI_TOKEN }}

      - name: Pull images
        run: |
          docker compose \
            --project-directory deploy \
            --project-name ${{ env.PROJECT_NAME }} \
            pull

      - name: Migrate DB
        run: |
          docker compose \
            --project-directory deploy \
            --project-name ${{ env.PROJECT_NAME }} \
            run --rm control-panel-service \
            uv run --active --no-sync --directory=backend/control-panel-service alembic upgrade head

      - name: Deploy
        run: |
          docker compose \
            --project-directory deploy \
            --project-name ${{ env.PROJECT_NAME }} \
            up --detach --remove-orphans

  deploy-production:
    name: Deploy Production
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [self-hosted, Linux, production]
    environment:
      name: Production
      url: https://to.profcomff.com/
    permissions:
      packages: read
    env:
      PROJECT_VERSION: latest
      PROJECT_NAME: com_profcomff_redirect
      CONTAINER_SUFFIX: ""
      DB_DSN: ${{ secrets.DB_DSN }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
      BASE_URL: ${{ vars.BASE_URL }}
      OIDC_CONFIGURATION_URI: ${{ vars.OIDC_CONFIGURATION_URI }}
      OIDC_CLIENT_ID: ${{ vars.OIDC_CLIENT_ID }}
      OIDC_ADMIN_CLAIM: ${{ vars.OIDC_ADMIN_CLAIM }}
      OIDC_ADMIN_CLAIM_VALUE: ${{ vars.OIDC_ADMIN_CLAIM_VALUE }}
      ALLOWED_DOMAINS: ${{ vars.ALLOWED_DOMAINS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to git.dyakov.space
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: robot-profcomff
          password: ${{ secrets.DYAKOVSPACE_CI_TOKEN }}

      - name: Pull images
        run: |
          docker compose \
            --project-directory deploy \
            --project-name ${{ env.PROJECT_NAME }} \
            pull

      - name: Migrate DB
        run: |
          docker compose \
            --project-directory deploy \
            --project-name ${{ env.PROJECT_NAME }} \
            run --rm control-panel-service \
            uv run --active --no-sync --directory=backend/control-panel-service alembic upgrade head

      - name: Deploy
        run: |
          docker compose \
            --project-directory deploy \
            --project-name ${{ env.PROJECT_NAME }} \
            up --detach --remove-orphans
